name: places
description: A mobile app with a list of interesting places and attractions for traveling around the world.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  
  flutter:
    sdk: flutter

  # Network
  dio: ^4.0.0

  # State management
  flutter_bloc: ^8.0.1
  provider: ^6.0.1

  # Storage
  shared_preferences: ^2.0.11
  drift: ^1.2.0
  sqlite3_flutter_libs: ^0.5.3
  path_provider: ^2.0.8
  path: ^1.8.0

  # UI
  flutter_switch: ^0.3.2
  flutter_svg: ^0.22.0
  photo_view: ^0.13.0
  image_picker: ^0.8.4+4
  cached_network_image: ^3.2.0

  # Lint
  #surf_lint_rules: ^1.4.1

  # Map
  yandex_mapkit: ^2.0.1

  # Other
  equatable: ^2.0.3
  rxdart: ^0.27.3
  mime_type: ^1.0.0
  intl: ^0.17.0

dev_dependencies:
  
  flutter_test:
    sdk: flutter
    
  build_runner: ^2.1.4
  dart_code_metrics: ^4.6.0
  drift_dev: ^1.2.1


flutter:
  uses-material-design: true

  assets:
    - res/
    - res/fonts/
    - res/icons/
    - res/images/