name: places
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_code_metrics: ^4.6.0
  dio: ^4.0.0
  equatable: ^2.0.3
  file_picker: ^4.2.1
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.2
  flutter_svg: ^0.22.0
  flutter_switch: ^0.3.2
  image_picker: ^0.8.4+4
  mobx: ^2.0.5
  open_file: ^3.2.1
  photo_view: ^0.13.0
  provider: ^6.0.1
  
  

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.4


flutter:
  uses-material-design: true

  assets:
    - res/
    - res/fonts/
    - res/icons/