name: places
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^8.0.1

  # Network
  dio: ^4.0.0
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  file_picker: ^4.2.1

  flutter_svg: ^0.22.0
  flutter_switch: ^0.3.2
  image_picker: ^0.8.4+4
  
  intl: ^0.17.0
  mime_type: ^1.0.0
  
  open_file: ^3.2.1
  photo_view: ^0.13.0
  provider: ^6.0.1
  
  relation: ^3.1.0
  rxdart: ^0.27.3

  # cache images
  cached_network_image: ^3.2.0
  

dev_dependencies:
  
  flutter_test:
    sdk: flutter
    
  dart_code_metrics: ^4.6.0
  build_runner: ^2.1.4


flutter:
  uses-material-design: true

  assets:
    - res/
    - res/fonts/
    - res/icons/
    - res/images/